### ISSUE TITLE
La interfaces no deben tener código ni métodos static

### ISSUE THREAD

**Issue by gankbanger** [Rafa3lP3rez/TurnosMedicos#1]
https://github.com/Rafa3lP3rez/TurnosMedicos/blob/50dadfc55a00fef9349f2c11a223bbf1144ab134/src/main/java/com/consultoriomedico/repository/RepoUsuarios.java#L6-L15

Las interfacez deben simplemente definir un _contrato_ :

1. No deben definir métodos _static_
2. No es necesario colocar `public`, todos sus métodos lo son por defecto.

También es bueno tratar en lo posible de mantener chequeo de tipos: En otras palabra, no regresar `Object[]`, mejor `Usuario[]` y aún mejor, `List<Usuario>` 

Es decir:

```java
public interface RepoUsuarios {
    void grabar(Object usuario) throws IOException;

    List<Usuario> listarUsuarios() throws IOException;

    Usuario buscarPorId() throws IOException;
}
```

**Comment by RenattoB** [comment]
Se corrigio el issue presentado
