### ISSUE TITLE
La depencencia entre GestionUsuarioImpl y RepoUsuarioImpl debe ser indirecta via la interfaz RepoUsuario

### ISSUE THREAD

**Issue by gankbanger** [Rafa3lP3rez/TurnosMedicos#2]
https://github.com/Rafa3lP3rez/TurnosMedicos/blob/50dadfc55a00fef9349f2c11a223bbf1144ab134/src/main/java/com/consultoriomedico/service/GestionUsuariosImpl.java#L64

En lugar de hacer llamados a métodos _static_ de `RepoUsuarioImpl` , `GestionUsuarioImpl` debería recibir una referencia a una instancia de `RepoUsuarioImpl` y utilizar esta referencia dentro del código

```java
public class GestionUsuariosImpl implements GestionUsuarios {
    private RepoUsuarios repo;

    private GestionUsuariosImpl(RepoUsuarios repositorio){
        repo = repositorio;
    }

    public void crearUsuario(){
        // código ...
        repo.crearUsuario(usuario);
    }
```

**Comment by RenattoB** [comment]
Se actualizaron los métodos, se llamaran a través del builder que devolverá la instancia del objeto.
