### ISSUE TITLE
Tipar el retorno del método listar usuarios 

### ISSUE THREAD

**Issue by gankbanger** [Rafa3lP3rez/TurnosMedicos#3]
https://github.com/Rafa3lP3rez/TurnosMedicos/blob/d6726cb9c145e26155eb7bf9a8f01d556166d9b3/src/main/java/com/consultoriomedico/repository/RepoUsuarios.java#L9

Es mejor práctica tipar el retorno. En este caso, `List<Usuario>` en lugar de `Object[]`

**Comment by RenattoB** [comment]
Se separa el metodo "listarUsuario" en "listarDoctores" y "listarPacientes" para retornar el tipo de dato que corresponde.
